name: api_analysis
description: API analysis framework
publish_to: none # DO NOT PUBLISH THIS!!!

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.0.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
